### ISSUE TITLE
Going to main menu by itself without proper login

### ISSUE THREAD

**Issue by trippleflux** [mwage/DarkRift2_Boilerplate#5]
It seems that upon starting the launcher scene, the login scene changing itself into mainmenu without proper login, i have checked everywhere in awake or start function to properly checked it but it's still 'passthrough' itself into mainmenu scene  : 
```
            if (LoginManager.IsLoggedIn)
            {
                gameObject.SetActive(false);
            }
            else
            {
                SceneManager.LoadScene("Login");
            }
```

My console is spammed with the following : 
```
Player not logged in!
FriendManager.OnDataHandler()    Assets/Scripts/Friends/FriendManager.cs:360

DarkRift.Client.Unity.<Client_MessageReceived>c__AnonStorey2.<>m__0()    Assets/DarkRift/Plugins/Client/UnityClient.cs:305

ActionDispatcherTask.Execute()

Dispatcher.ExecuteDispatcherTasks()

UnityClient.Update()    Assets/DarkRift/Plugins/Client/UnityClient.cs:214
```

Here is the gif showing off the issue : 
![error](https://user-images.githubusercontent.com/1216215/41409755-7bdca97a-7001-11e8-9bb6-5e0d8c8d3188.gif)

**Comment by mwage** [comment]
Closing it, since we already figured out what the issue was. Those evil interfering unrelated plugins. :)
